Repository Samograje/co-gdzie-kiedy, pull requests merged in 2020-01, with the labels that each got.

#124 Ignorowanie warningów pochodzących z bibliotek
  frontend/src/index.js
Labels: bug

#131 Poprawa metody generującej nazwę afiliacji
  backend/src/main/java/org/polsl/backend/service/AffiliationService.java
Labels: bug

#133 Ustawienie numeru inwentarzowego przy pobieraniu jednego zestawu o da…
  backend/src/main/java/org/polsl/backend/service/ComputerSetService.java
Labels: backend, bug

#130 Dodanie filtrów do tabeli
  frontend/src/APIClient.js
  frontend/src/components/affiliations/AffiliationsListComponent.jsx
  frontend/src/components/affiliations/AffiliationsListContainer.jsx
  frontend/src/components/computersets/ComputerSetsListComponent.jsx
  frontend/src/components/computersets/ComputerSetsListContainer.jsx
  frontend/src/components/hardware/HardwareListComponent.jsx
  frontend/src/components/hardware/HardwareListContainer.jsx
  frontend/src/components/software/SoftwareListComponent.jsx
  frontend/src/components/software/SoftwareListContainer.jsx
  frontend/src/components/ui/responsivetable/MobileTable.jsx
  frontend/src/components/ui/responsivetable/ResponsiveTable.jsx
  frontend/src/components/ui/responsivetable/WideTable.jsx
Labels: enhancement

#146 Powiadamianie o podaniu błędnej nazwy ekranu w metodzie push()
  frontend/src/withCustomRouting.js
Labels: enhancement

#147 Utworzenie formularza przynależności
  backend/src/main/java/org/polsl/backend/controller/AffiliationController.java
  backend/src/main/java/org/polsl/backend/dto/affiliation/AffiliationDTO.java
  backend/src/main/java/org/polsl/backend/dto/affiliation/AffiliationListOutputDTO.java
  backend/src/main/java/org/polsl/backend/service/AffiliationService.java
  backend/src/test/java/org/polsl/backend/AffiliationControllerIntegrationTest.java
  frontend/src/components/affiliations/AffiliationDetailsComponent.jsx
  frontend/src/components/affiliations/AffiliationDetailsContainer.jsx
  frontend/src/components/affiliations/AffiliationsListContainer.jsx
Labels: enhancement, frontend

#164 Poprawka dla serwisu hardware (Filtrowanie)
  backend/src/main/java/org/polsl/backend/controller/HardwareController.java
  backend/src/main/java/org/polsl/backend/service/HardwareService.java
  backend/src/test/java/org/polsl/backend/HardwareControllerIntegrationTest.java
  frontend/src/components/hardware/HardwareListContainer.jsx
Labels: backend

#166 Poprawa wyświetlania listy danych w komórkach tabel
  frontend/src/components/ui/responsivetable/MobileTable.jsx
  frontend/src/components/ui/responsivetable/WideTable.jsx
Labels: frontend

#115 Uwzględnienie problemów z uruchamianiem aplikacji mobilnej w dokumentacji
  frontend/README.md
Labels: documentation

#170 Modernizacja listy afiliacji: nowe kolumny, potwierdzanie usunięcia
  backend/package-lock.json
  backend/src/main/java/org/polsl/backend/dto/affiliation/AffiliationListOutputDTO.java
  backend/src/main/java/org/polsl/backend/service/AffiliationService.java
  backend/src/test/java/org/polsl/backend/AffiliationControllerIntegrationTest.java
  frontend/src/components/affiliations/AffiliationsListComponent.jsx
  frontend/src/components/affiliations/AffiliationsListContainer.jsx
Labels: enhancement

#175 Odświeżanie ekranów na Androidzie.
  frontend/src/components/affiliations/AffiliationsListContainer.jsx
  frontend/src/components/computersets/ComputerSetsListContainer.jsx
  frontend/src/components/hardware/HardwareListContainer.jsx
  frontend/src/components/homepage/HomepageContainer.jsx
  frontend/src/components/software/SoftwareListContainer.jsx
  frontend/src/components/ui/qr/ScanScreenComponent.jsx
  frontend/src/withCustomRouting.js
Labels: android, bug

#198 Przekierowanie do listy po dodaniu sprzętu
  frontend/src/components/hardware/HardwareDetailsComponent.jsx
  frontend/src/components/hardware/HardwareDetailsContainer.jsx
Labels: bug, frontend

#197 Przygotowanie pod zadanie z wyświetlaniem usuniętych elementów
  backend/src/main/java/org/polsl/backend/controller/AffiliationController.java
  backend/src/main/java/org/polsl/backend/controller/ComputerSetController.java
  backend/src/main/java/org/polsl/backend/controller/HardwareController.java
  backend/src/main/java/org/polsl/backend/controller/SoftwareController.java
  backend/src/main/java/org/polsl/backend/dto/affiliation/AffiliationListOutputDTO.java
  backend/src/main/java/org/polsl/backend/dto/affiliation/AffiliationOutputDTO.java
  backend/src/main/java/org/polsl/backend/dto/computerset/ComputerSetListOutputDTO.java
  backend/src/main/java/org/polsl/backend/dto/hardware/HardwareListOutputDTO.java
  backend/src/main/java/org/polsl/backend/dto/software/SoftwareListOutputDTO.java
  backend/src/main/java/org/polsl/backend/service/AffiliationService.java
  backend/src/main/java/org/polsl/backend/service/ComputerSetService.java
  backend/src/main/java/org/polsl/backend/service/HardwareService.java
  backend/src/main/java/org/polsl/backend/service/SoftwareService.java
  frontend/src/APIClient.js
  frontend/src/components/affiliations/AffiliationsListContainer.jsx
  frontend/src/components/ui/responsivetable/MobileTable.jsx
  frontend/src/components/ui/responsivetable/WideTable.jsx
Labels: backend

#202 Rozbudowa mechanizmu filtrowania
  backend/src/main/java/org/polsl/backend/controller/AffiliationController.java
  backend/src/main/java/org/polsl/backend/controller/ComputerSetController.java
  backend/src/main/java/org/polsl/backend/controller/HardwareController.java
  backend/src/main/java/org/polsl/backend/controller/SoftwareController.java
  backend/src/main/java/org/polsl/backend/filtering/Search.java
  backend/src/main/java/org/polsl/backend/filtering/SearchSpecification.java
  backend/src/main/java/org/polsl/backend/filtering/SpecificationsBuilder.java
  backend/src/main/java/org/polsl/backend/service/filtering/SearchCriteria.java
  backend/src/main/java/org/polsl/backend/service/filtering/SearchService.java
  backend/src/main/java/org/polsl/backend/service/filtering/SearchSpecification.java
  backend/src/main/java/org/polsl/backend/service/filtering/SearchType.java
  backend/src/main/java/org/polsl/backend/service/filtering/SpecificationBuilder.java
  backend/src/main/java/org/polsl/backend/specification/AffiliationSpecification.java
  backend/src/main/java/org/polsl/backend/specification/ComputerSetSpecification.java
  backend/src/main/java/org/polsl/backend/specification/HardwareSpecification.java
  backend/src/main/java/org/polsl/backend/specification/SoftwareSpecification.java
  frontend/src/APIClient.js
  frontend/src/components/hardware/HardwareDetailsContainer.jsx
  frontend/src/components/hardware/HardwareListContainer.jsx
Labels: bug, enhancement
